# This file is covered by the LICENSE file in the root of this project.


#ORIGINAL FILE IS ALTERED FOR BINARY CLASSIFCATION 
#2022 Johan Bergius.

labels:
  0: "Inv Snow" #added JB
  1: "Snow" #added JB 
color_map: # bgr
  0: [10, 200, 0] #changed
  1: [255, 255, 255] #added JB 
  
content: # as a ratio with the total number of points
  0: 0.8175302573170367  #added JB 
  1: 0.18246974268296328  #added JB 
# classes that are indistinguishable from single scan or inconsistent in
# ground truth are mapped to their closest equivalent
learning_map:
  0: 0     # "Inv Snow
  1: 1     # " snow
learning_map_inv: # inverse of previous map
  0: 0     # "Inv Snow
  1: 1     # " snow
learning_ignore: # Ignore classes
  0: False     # "Inv Snow
  1: False     # " snow  
split: # sequence numbers
  train:
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 20
    - 22
    - 23
    - 24
    - 26
  valid:
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 20
    - 22
    - 23
    - 24
    - 26
  test:
    - 28
    #- 30
    #- 34
    #- 35
    #- 36
    #- 76